/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf8fd',
        'surface-dim': '#dbd9de',
        'surface-bright': '#fbf8fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2f7',
        'surface-container': '#f0edf2',
        'surface-container-high': '#eae7ec',
        'surface-container-highest': '#e4e1e6',
        'on-surface': '#1b1b1f',
        'on-surface-variant': '#4a4455',
        'inverse-surface': '#303034',
        'inverse-on-surface': '#f2f0f5',
        outline: '#7b7487',
        'outline-variant': '#ccc3d8',
        'surface-tint': '#732ee4',
        primary: '#630ed4',
        'on-primary': '#ffffff',
        'primary-container': '#7c3aed',
        'on-primary-container': '#ede0ff',
        'inverse-primary': '#d2bbff',
        secondary: '#625595',
        'on-secondary': '#ffffff',
        'secondary-container': '#c6b7ff',
        'on-secondary-container': '#524584',
        tertiary: '#4f4d5e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#676577',
        'on-tertiary-container': '#e7e4f8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#eaddff',
        'primary-fixed-dim': '#d2bbff',
        'on-primary-fixed': '#25005a',
        'on-primary-fixed-variant': '#5a00c6',
        'secondary-fixed': '#e7deff',
        'secondary-fixed-dim': '#ccbeff',
        'on-secondary-fixed': '#1e0e4e',
        'on-secondary-fixed-variant': '#4a3d7c',
        'tertiary-fixed': '#e4e0f5',
        'tertiary-fixed-dim': '#c7c4d8',
        'on-tertiary-fixed': '#1b1a29',
        'on-tertiary-fixed-variant': '#464555',
        background: '#fbf8fd',
        'on-background': '#1b1b1f',
        'surface-variant': '#e4e1e6',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        calm: '0 4px 12px rgba(99, 14, 212, 0.05)',
        'calm-lg': '0 12px 24px -8px rgba(99, 14, 212, 0.15)',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '0', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
        readable: '1024px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
    },
  },
  plugins: [],
}
